#!/usr/bin/env node
/**
 * GitHub Issue → PR Automation Agent
 * 
 * This script:
 * 1. Reads issue details from environment variables
 * 2. Creates a branch for the issue
 * 3. Writes an artifact file with the plan
 * 4. Makes a minimal safe code change (appends to ROADMAP.md)
 * 5. Commits and pushes the branch
 * 
 * Environment variables required:
 * - ISSUE_NUMBER: GitHub issue number
 * - ISSUE_TITLE: Issue title
 * - ISSUE_BODY: Issue body/description
 * - BASE_BRANCH: Base branch to create PR against (default: main)
 * - GH_AGENT_TOKEN: GitHub token for authentication (optional, for PR creation)
 */

import { execSync } from 'child_process';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';

const ISSUE_NUMBER = process.env.ISSUE_NUMBER;
const ISSUE_TITLE = process.env.ISSUE_TITLE || '';
const ISSUE_BODY = process.env.ISSUE_BODY || '';
const BASE_BRANCH = process.env.BASE_BRANCH || 'main';

if (!ISSUE_NUMBER) {
  console.error('Error: ISSUE_NUMBER environment variable is required');
  process.exit(1);
}

// Create branch name: agent/issue-<nr>-<slug>
function createBranchName(issueNumber, title) {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 50);
  return `agent/issue-${issueNumber}-${slug || 'untitled'}`;
}

const branchName = createBranchName(ISSUE_NUMBER, ISSUE_TITLE);

console.log(`[agent] Processing issue #${ISSUE_NUMBER}`);
console.log(`[agent] Title: ${ISSUE_TITLE}`);
console.log(`[agent] Branch: ${branchName}`);

try {
  // 1. Ensure we're on base branch and up to date
  console.log(`[agent] Checking out ${BASE_BRANCH}...`);
  execSync(`git checkout ${BASE_BRANCH}`, { stdio: 'inherit' });
  execSync(`git pull origin ${BASE_BRANCH}`, { stdio: 'inherit' });

  // 2. Create and checkout new branch
  console.log(`[agent] Creating branch ${branchName}...`);
  execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });

  // 3. Create artifact directory if it doesn't exist
  const artifactDir = 'agent_artifacts';
  if (!existsSync(artifactDir)) {
    execSync(`mkdir -p ${artifactDir}`, { stdio: 'inherit' });
  }

  // 4. Write artifact file
  const artifactPath = join(artifactDir, `issue-${ISSUE_NUMBER}-plan.md`);
  const artifactContent = `# Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}

**Created**: ${new Date().toISOString()}
**Branch**: \`${branchName}\`

## Issue Description

${ISSUE_BODY}

## Plan

This is an automated branch created by the GitHub Issue → PR agent.

The agent will:
1. ✅ Create branch: \`${branchName}\`
2. ✅ Write this artifact file
3. ✅ Make a minimal safe code change (append to ROADMAP.md)
4. ✅ Commit and push the branch

## Next Steps

- Review the issue requirements
- Implement the necessary changes
- Update this plan as needed
- Create a PR when ready

---
*This file was automatically generated by the GitHub Issue → PR automation agent.*
`;

  console.log(`[agent] Writing artifact: ${artifactPath}`);
  writeFileSync(artifactPath, artifactContent, 'utf-8');

  // 5. Make minimal safe code change: append to ROADMAP.md
  const roadmapPath = 'ROADMAP.md';
  if (existsSync(roadmapPath)) {
    const roadmapContent = readFileSync(roadmapPath, 'utf-8');
    const newEntry = `\n## Agent\n\nThis section is automatically updated by the GitHub Issue → PR automation agent.\n\n- Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE} (branch: \`${branchName}\`)\n`;
    
    // Only append if not already present
    if (!roadmapContent.includes(`Issue #${ISSUE_NUMBER}:`)) {
      const updatedContent = roadmapContent + newEntry;
      writeFileSync(roadmapPath, updatedContent, 'utf-8');
      console.log(`[agent] Updated ${roadmapPath}`);
    } else {
      console.log(`[agent] ${roadmapPath} already contains entry for issue #${ISSUE_NUMBER}`);
    }
  } else {
    console.log(`[agent] Warning: ${roadmapPath} not found, skipping update`);
  }

  // 6. Stage changes
  console.log(`[agent] Staging changes...`);
  execSync('git add agent_artifacts/ ROADMAP.md', { stdio: 'inherit' });

  // 7. Commit
  const commitMessage = `agent: create branch for issue #${ISSUE_NUMBER}

- Create artifact: agent_artifacts/issue-${ISSUE_NUMBER}-plan.md
- Update ROADMAP.md with issue reference

Issue: #${ISSUE_NUMBER}
Title: ${ISSUE_TITLE}
`;
  console.log(`[agent] Committing changes...`);
  execSync(`git commit -m "${commitMessage.replace(/"/g, '\\"')}"`, { stdio: 'inherit' });

  // 8. Push branch
  console.log(`[agent] Pushing branch ${branchName}...`);
  execSync(`git push -u origin ${branchName}`, { stdio: 'inherit' });

  console.log(`[agent] ✅ Success! Branch ${branchName} created and pushed.`);
  console.log(`[agent] Next: Create a PR from ${branchName} to ${BASE_BRANCH}`);

} catch (error) {
  console.error(`[agent] ❌ Error: ${error.message}`);
  process.exit(1);
}
